version: "3.2"
services:    
    php:
        build:
            context: ./Php/
            dockerfile: Dockerfile-Php
        working_dir: /
        tty: true
        networks:
          - backend
        volumes:
            - ./Source:/var/www/html/
    #postgres:
    #    working_dir: /
    #    image: postgres:9.5
    #    restart: always
    #    ports:
    #        - 5432:5432
    #    tty: true
    #    environment:
    #        - POSTGRES_DB=db_test
    #        - POSTGRES_USER=postgres
    #        - POSTGRES_PASSWORD=123456
    apache:
        build:
            context: ./Apache/
            dockerfile: Dockerfile-Apache
        working_dir: /var/www/html
        ports:
			# HOST:DOCKER
            - 8080:80
        tty: true
        networks:
          - frontend
          - backend
        depends_on:
            - php
            #- postgres
        
networks:
  frontend:
  backend:
    
        