version: "3.2"
services:
    php:
        build:
            context: ./Php/
            dockerfile: Dockerfile-Php
        networks:
            - backend
        volumes:
            # HOST:DOCKER
            - ./Source/:/var/www/html/
            # Not mount folder buildtime, ONLY attached to DOCKER
            - /var/www/html/node_modules
            - /var/www/html/vendor
        ports:
            # HOST:DOCKER
            - "1111:22"
        working_dir: /var/www/html/
    postgres:
        image: postgres:9.5
        build:
            context: ./Postgres/
            dockerfile: Dockerfile-Postgres
        restart: always
        ports:
            # HOST:DOCKER
            - "5432:5432"
            - "2222:22"
        networks:
            - backend
        environment:
            - POSTGRES_MULTIPLE_DATABASES=db_test,db_test2
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - ./Postgres/initdb/:/docker-entrypoint-initdb.d/
        working_dir: /
    apache:
        build:
            context: ./Apache/
            dockerfile: Dockerfile-Apache
        networks:
            - backend
            - frontend
        ports:
            # HOST:DOCKER
            - "80:80"
            - "3333:22"
        depends_on:
            - php
            - postgres
        working_dir: /usr/local/apache2/
networks:
    frontend:
    backend:
    
        