version: "3.2"
services:
    php:
        build:
            context: ./Php/
            dockerfile: Dockerfile-Php
        networks:
            - backend
        volumes:
            # HOST:DOCKER
            #- ./Source/:/var/www/html/
            - C:\Users\QuocMinh\MINH\laravel_src:/var/www/html/
            # Not mount folder buildtime, ONLY attached to DOCKER
            - /var/www/html/node_modules
            - /var/www/html/vendor
        ports:
            # HOST:DOCKER
            - "1111:22"
        working_dir: /var/www/html/
    postgres:
        #image: postgres:9.5
        build:
            context: ./Postgres/
            dockerfile: Dockerfile-Postgres
        restart: always
        ports:
            # HOST:DOCKER
            - "5432:5432"
            - "2222:22"
        networks:
            - backend
        environment:
            - POSTGRES_MULTIPLE_DATABASES=db_test,db_test2
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - ./Postgres/initdb/:/docker-entrypoint-initdb.d/
    mysql:
        build:
            context: ./MySQL/
            dockerfile: Dockerfile-MySQL
        restart: always
        ports:
            # HOST:DOCKER
            - "3306:3306"
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=123456
            #- MYSQL_USER=dev
            #- MYSQL_PASSWORD=123456
    apache:
        build:
            context: ./Apache/
            dockerfile: Dockerfile-Apache
        networks:
            - backend
            - frontend
        ports:
            # HOST:DOCKER
            - "80:80"
            - "4444:22"
        depends_on:
            - php
            - postgres
        volumes:
            # HOST:DOCKER
            #- ./Source/:/var/www/html/
            - C:\Users\QuocMinh\MINH\laravel_src:/var/www/html/
            # Not mount folder buildtime, ONLY attached to DOCKER
            - /var/www/html/node_modules
            - /var/www/html/vendor
        working_dir: /var/www/html/
networks:
    frontend:
    backend:
    
        