#https://github.com/SeleniumHQ/docker-selenium
version: "3"
services:
    selenium-hub:
        image: selenium/hub:3.141.59-mercury
        container_name: selenium-hub
        environment:
            - GRID_TIMEOUT=0
            - GRID_BROWSER_TIMEOUT=0
        ports:
            - "4444:4444"
    chrome_1:
        image: selenium/node-chrome-debug:3.141.59-mercury
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - VNC_NO_PASSWORD=1
            - NODE_MAX_INSTANCES=3
            - NODE_MAX_SESSION=3
            - HUB_PORT=4444
        ports:
            - "4445:5555"
            - "5900:5900"
    # chrome_2:
        # image: selenium/node-chrome-debug:3.141.59-mercury
        # volumes:
            # - /dev/shm:/dev/shm
        # depends_on:
            # - selenium-hub
        # environment:
            # - HUB_HOST=selenium-hub
            # - VNC_NO_PASSWORD=1
            # - NODE_MAX_INSTANCES=3
            # - NODE_MAX_SESSION=3
            # - HUB_PORT=4444
        # ports:
            # - "4446:5555"
            # - "5901:5900"
    # chrome_3:
        # image: selenium/node-chrome-debug:3.141.59-mercury
        # volumes:
            # - /dev/shm:/dev/shm
        # depends_on:
            # - selenium-hub
        # environment:
            # - HUB_HOST=selenium-hub
            # - VNC_NO_PASSWORD=1
            # - NODE_MAX_INSTANCES=3
            # - NODE_MAX_SESSION=3
            # - HUB_PORT=4444
        # ports:
            # - "4447:5555"
            # - "5902:5900"
    # chrome_4:
        # image: selenium/node-chrome-debug:3.141.59-mercury
        # volumes:
            # - /dev/shm:/dev/shm
        # depends_on:
            # - selenium-hub
        # environment:
            # - HUB_HOST=selenium-hub
            # - VNC_NO_PASSWORD=1
            # - NODE_MAX_INSTANCES=3
            # - NODE_MAX_SESSION=3
            # - HUB_PORT=4444
        # ports:
            # - "4448:5555"
            # - "5903:5900"
    # chrome_5:
        # image: selenium/node-chrome-debug:3.141.59-mercury
        # volumes:
            # - /dev/shm:/dev/shm
        # depends_on:
            # - selenium-hub
        # environment:
            # - HUB_HOST=selenium-hub
            # - VNC_NO_PASSWORD=1
            # - NODE_MAX_INSTANCES=3
            # - NODE_MAX_SESSION=3
            # - HUB_PORT=4444
        # ports:
            # - "4449:5555"
            # - "5904:5900"