FROM httpd:2.4.33-alpine
RUN apk update; \
    apk upgrade;

# Copy apache vhost file to proxy php requests to php-fpm container
#COPY connect-php-container.apache.conf /usr/local/apache2/conf/connect-php-container.apache.conf
#RUN echo "Include /usr/local/apache2/conf/connect-php-container.apache.conf" \
#    >> /usr/local/apache2/conf/httpd.conf

# COPY FILE CONF TO DOCKER
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY connect-php-container.apache.conf /usr/local/apache2/conf/connect-php-container.apache.conf