FROM php:7.1.23-fpm-alpine3.8
RUN apk update; \
    apk upgrade;

# INSTALL PHP EXTENSION	
RUN docker-php-ext-install pdo pdo_pgsql pgsql
RUN docker-php-ext-install sockets

# COPY file 
COPY php.ini /usr/local/etc/php/php.ini